### ISSUE TITLE
Patching program does not apply patch on files if working directory includes special characters

### ISSUE THREAD

**Issue by TheOpponent** [DerekPascarella/SakuraWarsColumns2-EnglishPatchDreamcast#1]
For example, if the program is run in a path with the name of the suggested GDI archive `Hanagumi Taisen Columns 2 v1.000 (1999)(Sega)(JP)[!]\`, it will report success but the patched_gdi directory will contain identical copies of the input files.

**Comment by DerekPascarella** [comment]
Thank you for the report.  The CLI tools I'm using under the hood for the GDI extract/rebuild could be to blame, although I am presently unable to replicate this issue.  I am testing using the source files below:

**Directory:**
Z:\dc\gdi\new\hanagumi_taisen_columns_2\Hanagumi Taisen Columns 2 v1.000 (1999)(Sega)(JP)[!]\

**File Listing:**
Hanagumi Taisen Columns 2 v1.000 (1999)(Sega)(JP)[!].gdi
track01.bin
track02.raw
track03.bin

**Comment by TheOpponent** [comment]
The path I used was `E:\Hanagumi Taisen Columns 2 v1.000 (1999)(Sega)(JP)[!]\`

I changed it to `E:\patch\` and the process worked as expected.

**Comment by DerekPascarella** [comment]
I have continued to test this issue and still cannot reproduce it.

**Comment by TheOpponent** [comment]
My own testing found that if the patch utility itself is in a path with `[ ] ( )`, which could happen if one were to extract the patch into the same directory as the GDI named after the archive as described in the first comment, then this issue occurs. The path to the GDI isn't affected by this. Running the program in a path like `C:\Users\Normal\Desktop\[\` is enough to cause the tools to fail silently, but in a path without brackets, it will successfully patch the GDI in a path like `E:\Hanagumi Taisen Columns 2 v1.000 (1999)(Sega)(JP)[!]\`.

**Comment by dotdissent** [comment]
I'm having the same problem. The patched_gdi files came out byte for byte identical. My location is "F:\Torrents\DreamcastJP\Hanagumi Taisen Columns 2 v1.000 (1999)(Sega)(JP)[!]"

It worked after changing to "F:\Torrents\DreamcastJP\C2"

**Comment by DerekPascarella** [comment]
Okay, I was able to reproduce this now.  I had to run the patcher itself from within the folder containing the extracted GDI (e.g. "Z:\some\folder\Hanagumi Taisen Columns 2 v1.000 (1999)(Sega)(JP)[!]\").

After some testing, it appears to be a strange issue with escaped characters for the directory/file parameters I'm passing to the GDI build/extract CLI utilities that I'm leveraging under-the-hood.  For some reason, they're not behaving as I'd typically expect.

**Comment by DerekPascarella** [comment]
Okay, I've narrowed it down to buidgdi.exe.  Below is an example of the command being passed to **powershell.exe** using a System.Diagnostics.Process call in C#:

`tools\buildgdi.exe -data 'Z:\Hanagumi Taisen Columns 2 v1.000 (1999)(Sega)(JP)[!]\patcher\1f8094ae-5efd-4053-9980-266e9a7c07ed_extracted' -ip 'Z:\Hanagumi Taisen Columns 2 v1.000 (1999)(Sega)(JP)[!]\patcher\1f8094ae-5efd-4053-9980-266e9a7c07ed_extracted\bootsector\IP.BIN' -output 'Z:\Hanagumi Taisen Columns 2 v1.000 (1999)(Sega)(JP)[!]\patcher\1f8094ae-5efd-4053-9980-266e9a7c07ed' -gdi 'Z:\Hanagumi Taisen Columns 2 v1.000 (1999)(Sega)(JP)[!]\patcher\1f8094ae-5efd-4053-9980-266e9a7c07ed\disc.gdi' -raw`

While this command successfully executes manually via the PowerShell terminal, the special characters in the directory name cause it to fail.  Interestingly enough, only the directory name has to be "normalized", not the .GDI filename itself.

I'll keep working on it.

**Comment by DerekPascarella** [comment]
Okay, solved!  Version 0.2 of the patcher has been uploaded to the main repository and I've also repacked the v1.0 patch .ZIP in the "Releases" section to include the updated patcher.
